language: node_js
node_js:
- node
after_success:
- tsc
deploy:
  provider: heroku
  api_key:
    secure: CL6rVX6pmb+KzncEhbxZwQvEdBInBgqwRlffVapUmMRx/JXblpqXhKZ1qNawuVfyJY44aqZ7JWhDSqvFtoWbT6+HPyLwELxDhCLHqfTea/VBrH5JV/t0PjftsQmLITw9sfCZow2XyL8ZWoszaDpAyShYaeoxJFLQJb6Pg/+VvEOONUkcZEGb9lDbiiWF6v3aIzPMRjJBLMg1ZbQbSMj/PytNOkyik+Eclw+zgOs2ZRiBZzIe9MhvbyrD++6p2ua9W0gKq8uxvp1srJjrx2onGANPKbXDpIgw9oR2RgCB9+9FOOTCacSulYA1uO07Ub5uEApExOodNUfr+x8nEDVZOTPTSeF/9GsLG3Rg/+942ucbinA3qOTOqWz84/MUw3iX6wzWYB2ECmWEdvjLwiIlfNuPPSFz2xvbiQjc8LsJR/k1EWUdof8u0AMfc8cix+eXEiVF8g8izJiLYl19pF9K3WtTTE91/R4C0rZzWtTLws1ukDDsJfP09K6+xmr5yVkEATNVNbGdVFVl8e748/ealMKmcD4wEPuojkUdS4ETPJXLYZnDKy7UjNbPzbI3sxsj2cT9I27h4DznsqRSXaI7ELGPVPVV4o3D2jTr5ucRHhcVixDxRcgAqhP18pkTcKaLWWAWvDVuJ3RlCKoH/gsLJaziS3wu1zZcf2Tf/RvpItw=
  app: dear47
