language: node_js
node_js:
- node
after_success:
- tsc
deploy:
  provider: heroku
  api_key:
    secure: ZFfN9aV/wbJ9pS7jdafCepCCk5YFFQ3uNb6kTwPEoJiqZ80ZuEZ3pR3uu4LoL3Y5nCUHas+Vo3kTOTygVZ8jXrgEW1HirylIY5Klx91rZTLwidKyCZNkJ57/3jwNIiEOlP1vrMuirybKkcrRn9velQCJqV/lUN8ACBhPqicCzBEdflesgMr0+LXsTCSsqOhwcsn1+HCstcfuODSUaotBADdfG5oWnQWEYII7MbbVEZw+BPofSF0k7FtnhaLlPZP92KCmk5e/FPIqR1BcwvRQc0JKqvgjoFY/BHZVeAndTENWIQHXsfhGuTnQQ+ZxnUgRpR1N7TK32/09Q7GTIOvfC65BrEsxgDlCC04C+drTI11Ck0isMe7hKbMUJs1gWXUoeUp7TfbSADBhDocuTKW10x+2iL2RndmOXpsZ3aIR0EZtsILaJDZjp3h18x6v4i/9WAqb3zAdSc/KLni3H5CnfnvVJSCyOkG9N+wZL1Pi2JqxYhrrcDpI47TLyZp21SF4ofWiE9s+StNDer8BnRPKjNTli1HJ0bz2C6u2Vz78kfaJyW8pqqsMwT5MojRHMmLxUYnlqWuHwAW04SLIFbvLOAiksNo6mj8tf8WgUGIyjzHPtyWY2fONbtznBfbMrmbh4SmdSgX1zEiEWVaEGUcMLfsYj4mxOOGEFnwHzAaNzn4=
  app: dear47