language: node_js
node_js:
- node
after_success:
- tsc
deploy:
  provider: heroku
  api_key:
    secure: KqAG1wrOdJq7cnFU4oapSIquWDcM3nyjh6cGySZ7YulaOUDV4kB2A6XbVLSAY8NWxJXgrub4NyT1ElnA5e06She1sb40Ao30WllA87oPKPuh6PHPGmT8juTxcs9ngWHzACu/yhfWnQCuMCLFKXcZBb/u4c5YzL4cb+We9981krO5tw5+6lgHhsAkZHcpPmpb9aWZieEcqzfhgzAziplR3P256ph5DcrnK9FLpMJrZVw2wt5n5z6qVQTeQFbCvpCfm63KW8guqE94B96lz/JhMZbKSkW76psveCGipXmZoccTTZPmqk2kz1OmtHPUz7ORp78UiQCsoWFyQ3v/QmU9//p3ZqOwm+8W/iuSm1a5wUHEhM8K2oIv3Xz9yoPc13p+2Eev0lDRBKFAQS3bjj2doCbW54rcqLY4UPOM3UWnAYfeL69V6D7sw+UAVJvf8sdGiqDmERY4rwTOXsDwvesp8AW700ih+WWj3cPWPdXS2JzSXia/Mxb48zopOoKxgQsJRfj20023F2tpxo8nDP7l8SUfnDxyAsfVk1LYNQHKHYKwtPPy28HKuVgy+3ePUfqk+7lxELa7ccLG8WQ+v4dnwV266L/z5tRDA0ArqFpUsZ90HmDOLianv8TZJEqimv0RErxjofDTgYZIwz/GrnEHmYnb9tVO41cYrMjovVmZRsc=
  app: dear47
